language: 'en-US'
early_access: false
enable_free_tier: true

reviews:
  profile: 'assertive'
  high_level_summary: true
  path_filters:
    - 'src/**'
    - '!dist/**'
    - '!node_modules/**'
    - '!public/**'
  auto_review:
    enabled: true
    drafts: false
