import {
  CheckCircle,
  Download,

  Play,
  ArrowRight,
} from 'lucide-react';
import { Link } from 'react-router-dom';
import { Titlebar } from '../layout/Titlebar';
import { DocsSection, CodeBlock, Callout, Prose, InlineCode } from './DocsSection';

export function GettingStartedPage() {
  return (
    <div className="h-screen flex flex-col bg-surface-950">
      <Titlebar />
      <div className="flex-1 overflow-y-auto">
        <div className="max-w-2xl mx-auto px-6 py-8 space-y-5 animate-fadeIn">
          <div className="mb-6">
            <h2 className="text-sm font-light tracking-[0.15em] uppercase text-accent-green/60">
              Getting Started
            </h2>
            <p className="text-xs text-zinc-500 mt-1">
              Set up distance-based path following for your FRC swerve robot.
            </p>
          </div>

          {/* Prerequisites */}
          <DocsSection icon={<CheckCircle size={13} />} title="Prerequisites">
            <Prose>
              <ul className="list-disc list-inside space-y-1 text-zinc-500">
                <li>WPILib 2025+</li>
                <li>CTRE Phoenix 6 (swerve drivetrain)</li>
                <li>AdvantageKit / AdvantageScope (optional, for logging)</li>
                <li>A swerve drivetrain subsystem extending <InlineCode>CommandSwerveDrivetrain</InlineCode></li>
              </ul>
              <Callout color="amber">
                This system is built for CTRE Phoenix 6 swerve projects generated by TunerX.
              </Callout>
            </Prose>
          </DocsSection>

          {/* Download Java Files */}
          <DocsSection icon={<Download size={13} />} title="Download Java Files">
            <Prose>
              <p>
                Go to the{' '}
                <Link to="/downloads" className="text-accent-green hover:underline">
                  Downloads page
                </Link>{' '}
                and download the ZIP. Copy the files into your robot project maintaining the package structure:
              </p>
              <CodeBlock>
{`src/main/java/frc/robot/
  commands/
    FollowPath.java
    AccelerationLimiter.java  (private — contact for access)
  utils/
    Motor.java                (private — contact for access)
    path/
      SplinePath.java
      VelocityProfile.java
      VelocityConstraints.java
      PathData.java

      RotationSupplier.java
      RotationSuppliers.java
      ProjectionResult.java
      CubicSegment.java`}
              </CodeBlock>
              <Callout color="amber">

                <InlineCode>AccelerationLimiter</InlineCode> and <InlineCode>Motor</InlineCode> are private files that require permission to use. Contact our team for access. Update the constants in <InlineCode>VelocityProfile</InlineCode> to match your robot.
              </Callout>
            </Prose>
          </DocsSection>

          {/* Minimal Autonomous Example */}
          <DocsSection icon={<Play size={13} />} title="Minimal Autonomous Example">
            <Prose>
              <p>A complete autonomous command using the Java export:</p>
              <CodeBlock>
{`public Command getAutonomousCommand() {
    // Auto-mirrors path when on red alliance
    PathData data = Paths.forAlliance(Paths.SPEAKER_CENTER);
    SplinePath spline = new SplinePath(data.controlPoints());

    return new FollowPath(drivetrain, spline,
            data.globalConstraints(), data.constraintZones())
        .withRotationSupplier(RotationSuppliers.fromZones(
            spline, data.headingWaypoints(),
            data.rotationZones()))
        .withLookahead(0.15, 0.15, 1.0)
        .withCrossTrackGains(3.0, 0.5);
}`}
              </CodeBlock>
              <p className="text-zinc-600">
                The path is distance-based — if the robot gets hit or stalls, the path "waits" for the robot to catch up rather than running ahead on a timer.
              </p>
            </Prose>
          </DocsSection>

          {/* Next Steps */}
          <DocsSection icon={<ArrowRight size={13} />} title="Next Steps">
            <Prose>
              <div className="space-y-2">
                <Link
                  to="/docs/robot-integration"
                  className="block neon-panel p-3 hover:border-accent-green/20 transition-colors"
                >
                  <div className="text-xs text-accent-green">Robot Integration</div>
                  <div className="text-[10px] text-zinc-600">
                    Per-axis overrides, rotation strategies, alliance mirroring, velocity profiling, tuning guide
                  </div>
                </Link>
                <Link
                  to="/docs/editor-guide"
                  className="block neon-panel p-3 hover:border-accent-green/20 transition-colors"
                >
                  <div className="text-xs text-accent-green">Editor Guide</div>
                  <div className="text-[10px] text-zinc-600">
                    Canvas interaction, constraint zones, rotation zones, charts, keyboard shortcuts
                  </div>
                </Link>
              </div>
            </Prose>
          </DocsSection>

          <div className="pb-8" />
        </div>
      </div>
    </div>
  );
}
